clicker_app/urls.py
from django.urls import path
from clicker_app import views

app_name = 'clicker_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('logout/', views.logout_view, name='logout'),
    path('add_points/', views.AddPoints.as_view(), name='add_points'),
    path('darkmode/', views.Darkmode.as_view(), name='darkmode'),
    path('purchase/', views.Purchase.as_view(), name='purchase'),
    path('upload_image', views.upload_image, name='upload'),
    path('social_login', views.social_login, name='social_login'),
]

clicker_png/urls.py
from clicker_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', views.index, name='index'),
    path('clicker_app/', include('clicker_app.urls')),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clicker_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import BooleanField, CharField, IntegerField


class Achievement(models.Model):
    name = CharField(max_length=128, unique=True)
    description = CharField(max_length=256)
    condition = IntegerField(default=0)
    current_score_achievement = BooleanField(default=False)

    def __str__(self):
        return self.name


class Upgrade(models.Model):
    name = CharField(max_length=128)
    cost = IntegerField(default=6969)  # Noticeable default value to be overriden
    effect = IntegerField(default=1)
    auto_click = BooleanField(default=True)

    def __str__(self):
        return self.name


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = IntegerField(default=0)
    lifetime_points = IntegerField(default=0)
    achievements = models.ManyToManyField(Achievement, blank=True)
    upgrades = models.ManyToManyField(Upgrade, through="OwnsUpgrade")
    darkmode = BooleanField(default=False)
    image = models.ImageField(upload_to="uploads/", default="../static/images/default-clicker.svg")

    def __str__(self):
        return self.user.username


class OwnsUpgrade(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    upgrade = models.ForeignKey(Upgrade, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

clicker_app/forms.py
from django import forms
from clicker_app.models import User, Account


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        labels = {
            'username': '',
            'email': '',
            'password': '',
        }
        help_texts = {
            'username': '',
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email: john@doe.com'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),
        }


class ImageUpload(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('image', )

clicker_app/views.py
from django.http.response import JsonResponse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from clicker_app.forms import UserForm, ImageUpload
from django.contrib.auth import authenticate, default_app_config, logout, login  # noqa: F401
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from clicker_app.models import Achievement, Upgrade, Account, OwnsUpgrade  # noqa: F401
from django.views import View
import os


def index(request):

    upgrades_list = Upgrade.objects.order_by("cost")
    upgrade_table_dict = {}

    for item in upgrades_list:
        upgrade_table_dict[item] = [item.cost, 0]

    if request.user.is_authenticated:
        purchased_list = OwnsUpgrade.objects.filter(account=request.user.account)
    else:
        purchased_list = []

    for p in purchased_list:
        if p.upgrade in upgrade_table_dict.keys():
            upgrade_table_dict[p.upgrade][1] = p.quantity

    # TODO: remove list index for whole leaderboard  when scrolling is implememnted
    leaderboard_list = Account.objects.order_by("-lifetime_points")

    ranking_list = Account.objects.order_by("-lifetime_points")

    clicks_per_second = 0
    for item in purchased_list:
        if item.upgrade.auto_click:
            clicks_per_second += item.upgrade.effect*item.quantity

    upgraded_click = 1
    for item in purchased_list:
        if not item.upgrade.auto_click:
            upgraded_click += item.upgrade.effect*item.quantity

    context_dict = {
        "leaderboard": leaderboard_list,
        "upgrade_table": upgrade_table_dict,
        "purchased_list": purchased_list,
        "ranking_list": ranking_list,
        "cps": clicks_per_second,
        "upgraded_click": upgraded_click,
    }
    response = render(request, "clicker_app/index.html", context=context_dict)
    return response


def about(request):
    response = render(request, "clicker_app/about.html")
    return response


def tutorial(request):
    response = render(request, "clicker_app/tutorial.html")
    return response


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse("clicker_app:index"))
            else:
                return HttpResponse("Your account is disabled")
        else:
            print("Invalid login details, please try again")
            return HttpResponse("Invalid login details supplied")
    else:
        response = render(request, "clicker_app/login.html")
        return response


def signup(request):
    registered = False  # registration unsuccessful initially
    if request.method == "POST":  # if form is post, attempt to process
        user_form = UserForm(request.POST)  # take information from form
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            account = Account.objects.create(user=user)
            account.user = user
            account.save()

            for upgrade_instance in Upgrade.objects.all():
                owns_upgrade = OwnsUpgrade.objects.get_or_create(account=account, upgrade=upgrade_instance)[0]
                owns_upgrade.save()

            registered = True  # save to databbase, registration successful
        else:
            print(user_form.errors)  # invalid attempt
    else:
        user_form = UserForm()  # give blank form ready to receive data
    response = render(request, "clicker_app/signup.html",
                      context={"user_form": user_form, "registered": registered})
    return response


def myaccount(request):

    if request.user.is_authenticated:
        purchased_list = OwnsUpgrade.objects.filter(account=request.user.account)
    else:
        return redirect(reverse("clicker_app:login"))
        purchased_list = []

    clicks_per_second = 0
    for item in purchased_list:
        if item.upgrade.auto_click:
            clicks_per_second += item.upgrade.effect*item.quantity

    all_achievements = Achievement.objects.all()

    context_dict = {
        "all_achievements": all_achievements,
        "cps": clicks_per_second,
    }

    response = render(request, "clicker_app/myaccount.html", context=context_dict)
    return response


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("clicker_app:index"))


class AddPoints(View):
    def post(self, request):
        a = request.POST.get("a", None)
        clicks = request.POST.get("clicks", 1)

        try:
            user_account = Account.objects.get(user__id=a)
        except Exception as e:
            print(e)
            return HttpResponse(-1)

        user_account.points = str(int(user_account.points) + int(clicks))
        user_account.lifetime_points = str(int(user_account.lifetime_points) + int(clicks))
        user_account.save()

        return JsonResponse({
            "points": user_account.points,
            "lifetime_points": user_account.lifetime_points,
        })


class Darkmode(View):
    def post(self, request):
        user_id = request.POST.get("user-id", None)

        try:
            user_account = Account.objects.get(user__id=user_id)
        except Exception as e:
            print(e)
            return HttpResponse(-1)

        user_account.darkmode = not user_account.darkmode
        user_account.save()

        return redirect(request.META.get("HTTP_REFERER"))


class Purchase(View):
    def post(self, request):
        user_id = request.POST.get("user-id", None)
        upgrade = request.POST.get("upgrade", None)

        try:
            user_account = Account.objects.get(user__id=user_id)
            upgrade_instance = Upgrade.objects.get(id=upgrade)
            owns_upgrade = OwnsUpgrade.objects.get_or_create(account=user_account, upgrade=upgrade_instance)[0]
        except Exception:
            return HttpResponse("-1?-1")

        cost_instance = int(owns_upgrade.upgrade.cost * (1.15 ** owns_upgrade.quantity))

        if user_account.points >= cost_instance:
            owns_upgrade.quantity += 1
            user_account.points = user_account.points - cost_instance
            user_account.save()
            owns_upgrade.save()
            cost_instance = int(owns_upgrade.upgrade.cost * (1.15 ** owns_upgrade.quantity))

        owns_upgrade.save()

        return JsonResponse({
            "cost_instance": str(cost_instance),
            "quantity": str(owns_upgrade.quantity),
        })


def upload_image(request):
    if request.method == "POST":
        image_form = ImageUpload(request.POST, request.FILES)
        if image_form.is_valid():
            image_form.save(commit=False)
            account_id = request.POST.get("user-id")
            if "image" in image_form.files.keys():
                new_image = image_form.files["image"]
                user_account = Account.objects.get(user__id=account_id)
                old_image = user_account.image
                if not os.path.samefile(os.path.join(os.getcwd(), "media", str(old_image)), os.path.join(os.getcwd(), "static/images/default-clicker.svg")):
                    old_image.delete()
                # TODO: maybe change image name to account_id new_image.name = account_id
                user_account.image = new_image
                user_account.save()

    return redirect(reverse("clicker_app:myaccount"))


def social_login(request):
    user = request.user
    try:
        Account.objects.get(user=user)
        return redirect(reverse("clicker_app:index"))
    except:  # noqa
        account = Account.objects.create(user=user)
        account.user = user
        account.save()
        return redirect(reverse("clicker_app:index"))

templates/clicker_app/about.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h2 class="margin15">
        About Clicker.png
    </h2>
    <plain>
        <div class="margin15">
            <div>Clicker.png is a clicker game based on other popular games like cookie clicker. </div>
            <div>Instructions on how to play it are in the tutorial tab.</div>
        </div>
        <div class="margin15">
            <div> This web application was developed as a group project (group 10A) for a Web Application Development course at the University of Glasgow.</div>
            <div>Group members are:
            <ul>
                <li>Thomas McCausland</li>
                <li>Finn Stockwell</li>
                <li>Julia Szuminska</li>
                <li>Hao Xu</li>
                <li>Sufiyyan Panezai</li>
            </ul></div>

        </div>
        <div class="margin15">
            <div> Github repository is available <a href="https://github.com/Hippodoodle/clicker.png" /> here </a> </div>
            <div>The web app was submitted on 6th of April 2021.</div>
        </div>
    </plain>



{% endblock %}
 

templates/clicker_app/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}" type="text/css">
    {% if user.account.darkmode %}
    <link rel="stylesheet" href="{% static 'dark.css' %}" type="text/css">
    {% else %}
    <link rel="stylesheet" href="{% static 'light.css' %}" type="text/css">
    {% endif %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <title>
        Clicker.png -
        {% block title_block %}
        default
        {% endblock %}
    </title>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/clicker-ajax.js' %}" crossorigin="anonymous"></script>
</head>

<body>
    <ul class="header">
        <li class="logo">
            <a href="{% url 'clicker_app:index' %}">
                <img src="{% static 'images/logo.png' %}" alt="Logo" />
            </a>
            <a href="{% url 'clicker_app:index' %}">
                Clicker.png
            </a>
        </li>
        <li class="spacer"></li>
        <li class="header-link"><a href="{% url 'clicker_app:index' %}">Home</a></li>
        <li class="header-link"><a href="{% url 'clicker_app:about' %}">About</a></li>
        <li class="header-link"><a href="{% url 'clicker_app:tutorial' %}">Tutorial</a></li>

        {% block top_right %}
        {% if user.is_authenticated %}
        <li class="header-link"><a href="{% url 'clicker_app:myaccount' %}">My Account</a></li>
        <li class="header-link"><a href="{% url 'clicker_app:logout' %}">Log out</a></li>
        {% else %}
        <li class="header-link"><a href="{% url 'clicker_app:login' %}">Log in</a></li>
        <li class="header-link"><a href="{% url 'clicker_app:signup' %}">Sign up</a></li>
        {% endif %}
        {% endblock %}
    </ul>

    {% block body_block %}
    default block
    {% endblock %}
</body>

</html>

templates/clicker_app/index.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load static %}

{% block title_block %}
Home
{% endblock %}

{% block body_block %}
<div class="body-container">

    <div class="leftpane">
        <div class="pane-title">STORE</div>

        <div class="shop">
            {% for key, value in upgrade_table.items %}
            <div id="upgrade-{{ key.id }}" class="shop-item" data-user="{{ user.id }}" data-upgrade="{{ key.id }}" data-csrf="{{ csrf_token }}">
                <div class="shop-item-name">
                    {{ key.name }}
                </div>
                <div class="shop-item-effect">
                    {{ key.effect }} {% if key.auto_click %} pixels/second {% else %} pixels/click {% endif %}
                </div>
                <div class="shop-item-numpurchased">
                    x{{ value.1 }}
                </div>
                <div id="upgrade-{{ key.id }}-price" class="shop-item-price">
                    <script>
                        x = {% for item in purchased_list %}{% if item.upgrade == key %} {{ item.upgrade.cost }} {% endif %} {% endfor %};
                        x = x * Math.pow(1.15, {% for item in purchased_list %}{% if item.upgrade == key %} {{ item.quantity }} {% endif %} {% endfor %});
                        document.getElementById("upgrade-{{ key.id }}-price").innerHTML = String(Math.floor(x)) + " pixels";
                    </script>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="middlepane">
        <div class="pane-title">
            <div class="stats-container">
                <div class="stat">
                    <span class="points-count">{{ user.account.points }}</span>
                    <img class="pixels-icon" alt="pixels" src="{% static 'images/pixel.svg' %}"/>
                </div>
                <div class="stat">
                    <span class="pixels-per-second">{{ cps }}</span>
                    <img class="pixels-icon"  alt="pixels" src="{% static 'images/pixel.svg' %}"/>/s
                </div>
                <div class="stat">
                    <span class="pixels-per-click">{{ upgraded_click }}</span>
                    <img class="pixels-icon"  alt="pixels" src="{% static 'images/pixel.svg' %}"/>/
                    <img class="cursor-icon"  alt="click" src="{% static 'images/cursor.svg' %}"/>
                </div>
            </div>
        </div>

        <div class="clicker-container">
            {% if user.is_authenticated %}
            <img src="{{ MEDIA_URL }}{{ user.account.image }}" alt="Clicker image" id="clicker" data-user="{{ user.id }}" data-csrf="{{ csrf_token }}" data-cps="{{ cps }}" data-click-upgraded="{{ upgraded_click }}"/>
            {% else %}
            <img src="{% static 'images/logo.png' %}" alt="Clicker image" id="clicker" data-user="{{ user.id }}" data-csrf="{{ csrf_token }}" data-cps="{{ cps }}" data-click-upgraded="{{ upgraded_click }}"/>
            {% endif %}
        </div>
    </div>

    <div class="rightpane">
        <div class="pane-title">LEADERBOARD</div>

        <div class="leaderboard-container">
            <div class="leaderboard">
                <table>
                    <tr>
                        <th>Rank</th>
                        <th>Username</th>
                        <th>Score</th>
                    </tr>
                    <tr>
                        {% for account in ranking_list %}
                        {% if account.user == request.user %}
                        <td>{{ forloop.counter }}</td>
                        <td>{{ account.user.username }}</td>
                        <td><span class="lifetime-points">{{ account.lifetime_points }}</span></td>
                        {%endif%}
                        {%endfor%}
                    </tr>
                    {% for account in leaderboard %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ account.user.username }}</td>
                        <td>
                            {% if account.user == request.user %}
                                <span class="lifetime-points">{{ account.lifetime_points }}</span>
                            {%else %}
                                {{ account.lifetime_points }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="spacer"></div>

        <div class="change-png-message">
            {% if user.is_authenticated %}
            <p id="upload-png-message">Go to <a href="{% url 'clicker_app:myaccount' %}">My Account</a> to change your clicker png!</p>
            {% else %}
            <p id="upload-png-message"><a href="{% url 'clicker_app:signup' %}">Sign Up</a> to upload your own clicker png!</p>
            {% endif %}
        </div>
    </div>

</div>
<script src="{% static 'js/auto-click.js' %}" crossorigin="anonymous"></script>
{% endblock %}

templates/clicker_app/login.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load static %}
{% load socialaccount %} 

{% block title_block %}
    LogIn
{% endblock %}

{% block body_block %}

<div class="login-container">
    <div class="login-card-background">
        <div class="login-card">
            <form method="post" action="{% url 'clicker_app:login' %}">
                {% csrf_token %}
                <input type="text" placeholder="Username" name="username">
                <input type="password" placeholder="Password" name="password">
                <div class="login-buttons">
                    <button class="signup-button" onclick="location.href='{% url 'clicker_app:signup' %}'" type="button">Sign Up</button>
                    <button type="submit" class="login-button">Log In</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/clicker_app/myAccount.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
My Account
{% endblock %}

{% block body_block %}
<h2 class="margin15">Welcome back {{user}}! </h2>
<div class="plain">
    <p>Total pixels earned: {{ user.account.lifetime_points }}</p>
    <p>Current number of pixels: {{ user.account.points }}</p>
    <p>Pixels per second: {{ cps }}</p>
</div>

<h3 class="margin15">Your achievements:</h3>

<div id="achievement-table-wrapper">
    <div id="achievement-table-scroll">
        <table>
            <thead>
                <tr>
                    <th><span class="achievement-title">Name</span></th>
                    <th><span class="achievement-title">Description</span></th>
                </tr>
            </thead>
            <tbody>
                {% for achievement in all_achievements %}
                <tr>
                    <td>{{ achievement.name }}</td>
                    {% if achievement.current_score_achievement %}
                        {% if user.account.points >= achievement.condition %}
                        <td>{{ achievement.description }}</td>
                        {% else %}
                        <td>?</td>
                        {% endif %}
                    {% else %}
                        {% if user.account.lifetime_points >= achievement.condition %}
                        <td>{{ achievement.description }}</td>
                        {% else %}
                        <td>?</td>
                        {% endif %}
                    {% endif %}
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>

<form method="POST" action="/clicker_app/darkmode/">
    {% csrf_token %}
    <input type="hidden" name="user-id" value="{{ user.id }}">
    <input type="submit" value="{% if user.account.darkmode %}Lightmode{% else %}Darkmode{% endif %}">
</form>

<div class="upload-png">
    <h3> You can upload your clicker photo here! </h3>
    <!--Buttons don't do anything yet. Should be upload, then update photo, then submit. 
        Or change to just one button upload, then update photo.-->
    <div class="right-centre margin15">
        <span class="margin15">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Upload file</button>
            </form>
        </span>
        <span class="margin15">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit</button>
            </form>
        </span>
    </div>

    <div class="bottom0-left0">
        <img id="icon" alt="Clicker Image" src="{% static 'images/logo.jpg'%}" />
    </div>
</div>
{% endblock %}

templates/clicker_app/myaccount.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load static %}

{% block title_block %}
My Account
{% endblock %}

{% block body_block %}
<div class="myaccount-body">

    <div class="myaccount-summary-colour">
        <div class="myaccount-summary">
            <div class="pane-title">{{user}}</div>

            <div class="myaccount-stats">
                <p>Total pixels earned: {{ user.account.lifetime_points }}</p>
                <p>Current number of pixels: {{ user.account.points }}</p>
                <p>Pixels per second: {{ cps }}</p>
            </div>

            <div class="darkmode">
                <form method="POST" action="/clicker_app/darkmode/">
                    {% csrf_token %}
                    <input type="hidden" name="user-id" value="{{ user.id }}">
                    <input type="submit" value="{% if user.account.darkmode %}Lightmode{% else %}Darkmode{% endif %}">
                </form>
            </div>
        </div>
    </div>

    <div class="myaccount-achievements">
        <div class="pane-title">Achievements</div>

        <div class="achievements-table-scroll">
            <table>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                {% for achievement in all_achievements %}
                <tr>
                    <td>{{ achievement.name }}</td>
                    {% if achievement.current_score_achievement %}
                        {% if user.account.points >= achievement.condition %}
                        <td>{{ achievement.description }}</td>
                        {% else %}
                        <td>???</td>
                        {% endif %}
                    {% else %}
                        {% if user.account.lifetime_points >= achievement.condition %}
                        <td>{{ achievement.description }}</td>
                        {% else %}
                        <td>???</td>
                        {% endif %}
                    {% endif %}
                </tr>
                {%endfor%}
            </table>
        </div>
    </div>

    <div class="myaccount-image">
        <div class="pane-title">You can upload your own clicker photo here</div>

        <div class="image-form">
            <form method="post" enctype="multipart/form-data" action="{% url 'clicker_app:upload' %}">
                {% csrf_token %}
                <input type="hidden" name="user-id" value ="{{ user.id }}">
                <input type="file" name ="image" value="image" accept="image/*">
                <input type="submit" name="submit" value="upload">
            </form>
        </div>

        <div class="image-preview">
            <img id="icon" alt="Clicker Image" src="{{ MEDIA_URL }}{{ user.account.image }}" />
        </div>
    </div>

</div>
{% endblock %}

templates/clicker_app/signup.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load static %}

{% block title_block %}
    SignUp
{% endblock %}

{% block body_block %}

<div class="signup-container">
    <div class="signup-card-background">
        <div class="signup-card">
            {% if not registered %}
            <form method="post" action="{% url 'clicker_app:signup' %}">
                {% csrf_token %}
                {{ user_form }}
                <div class="signup-buttons">
                    <button type="submit" class="signup-button">Sign Up</button>
                </div>
            </form>
            {% else %}
            <div> Thank you for signing up! </div>
            <div class="signup-buttons">
                <button class="login-button" onclick="location.href='{% url 'clicker_app:login' %}'" type="button">Log In</button>
            </div>
            {% endif %} 
        </div>
    </div>
</div>

{% endblock %}

templates/clicker_app/tutorial.html
<!DOCTYPE html>
{% extends 'clicker_app/base.html' %}
{% load static %}

{% block title_block %}
    Tutorial
{% endblock %}

{% block body_block %}
    <h3 class="margin15">Game tutorial</h3>
    <div class="plain">
        <strong>It is a clicker game. You get pixels when you click!</strong><div class="margin15"></div>

        <div>When you click the 'clicker' (the picture in the middle of Homepage) you will get a point - a pixel.</div>
        <div>You can buy improvements listed in store, it will make your clicks more powerful and speed up your pixel collection. </div>
        <div>There is a leader board showing you the scores of the best players but you need to sign up to make it to the leader board! </div>
        <div>Once you are signed up you can unlock achievements that will show up on your MyAccount page!</div>
        <div>Logged in users can also upload their own picture to be used as a clicker! You can do that on your MyAccount page. </div>
        <div class="margin15"></div>
        <strong>Have fun!</strong>
    </div>

{% endblock %}
 